### ISSUE TITLE
Return nullprt when there is no partent in DatasetImpl::getParent()

### ISSUE THREAD

**Issue by alxvth** [ManiVaultStudio/core#198]
Currently, calling `DatasetImpl::getParent()` when there is no parent dataset will result in a read access violation exception. 
https://github.com/hdps/core/blob/37f8238ca99b1080f03f949113e33ec11869afd4/HDPS/src/Set.cpp#L32

Maybe we could check if there is a parent dataset and return a `nullprt` in case there isn't.

**Comment by ThomasKroes** [comment]
Closed because it has been solved in the mean time: https://github.com/ManiVaultStudio/core/blob/1eb23340ee96be6aec9863fa41c7acf500fd2ac3/HDPS/src/Set.cpp#L57-L60
