### ISSUE TITLE
CI gives an error  "ERROR: conanfile didn't specify version" when the branch doesn't start with feature/<name>

### ISSUE THREAD

**Issue by sbvis** [ManiVaultStudio/core#280]
CI gives an error  "ERROR: conanfile didn't specify version" when the branch doesn't start with feature/<name>

**Comment by ThomasKroes** [comment]
@sbvis: is this issue still valid? Otherwise I'd like to close it.

**Comment by bldrvnlw** [comment]
I'd say close it now.
