### ISSUE TITLE
Multiple instances of the application settings panel can be opened.

### ISSUE THREAD

**Issue by thoellt** [ManiVaultStudio/core#359]
There should probably only be a single instance of the application settings panel. It is not a big issue, as the panels stay in sync but it does not seem like desired behavior.

Tested on macOS only.

Steps to reproduce:
1. Open App
1. Open Settings
1. Switch Focus to main Window
1. Open Settings menu entry and short cut will be active again, allowing to open a second settings window (can be repeated multiple times)

**Comment by ThomasKroes** [comment]
Solved in #426
