### ISSUE TITLE
Plugin objects do not get destructed

### ISSUE THREAD

**Issue by N-Dekker** [ManiVaultStudio/core#36]
It appears that `hdps::plugin` objects created by the plugin system do not get destructed, after they have been used.

(Eventually, they will get destroyed via `~MainWindow()`, by `~Core()`, but that happens only when the program is exited.)

@JulianThijssen wrote about this issue at https://biovault.slack.com/archives/CKLNDA6SY/p1581937798010500 (channel #hdps Monday February 17, 2020):

> It probably can be solved, but each type of plugin will have different conditions for being destructed
> Loaders should be removed after they are done loading. Views should be removed if the user closes the window for example. Analyses should be removed if the settings are closed
> In short loaders/writers can be removed automatically
> Data/views/analyses should be removed through some user interaction
> In the case of data it should be removed if all sets referencing it have been removed by the user

**Comment by ThomasKroes** [comment]
In its current state, view plugins are correctly destroyed (using `void PluginManager::destroyPlugin(plugin::Plugin* plugin)`). This is not the case yet for the other types of plugins. For this reason, I am moving this issue to the release 1.0 project.

**Comment by ThomasKroes** [comment]
This has been solved
