### ISSUE TITLE
Add event for DatasetRename

### ISSUE THREAD

**Issue by sbvis** [ManiVaultStudio/core#516]

**Comment by ThomasKroes** [comment]
I'd propose to close this issue. The `Dataset<DatasetImpl>` class already
has a `datasetGuiNameChanged()` qt signal.

**Comment by ThomasKroes** [comment]
Yes, that is correct.

The problem you describe seems like more of an edge case. I would get all
the datasets from the `mv::dataManager() getAllDatasets()` and register for
the name changes with those...

**Comment by ThomasKroes** [comment]
> Then every time a new dataset is added later, I will register for its name change event and add it to the existing Dataset variable?
yes

> Also, do I need to in some way deregister events if datasets are removed later?
No
