### ISSUE TITLE
fromVariantMap() called twice on all plugins

### ISSUE THREAD

**Issue by JulianThijssen** [ManiVaultStudio/core#540]
@ChangLi27 noticed that when loading a project, for every plugin in the workspace their fromVariantMap() function is called twice.

We traced it back to a bug in the ViewPluginDockWidget.cpp
![image](https://github.com/ManiVaultStudio/core/assets/2978176/857c94f7-87dc-4c6d-ac35-047f916be73f)

The last constructor is called, which in turn calls the first constructor via the `ViewPluginDockWidget()` in the initializer list. Both of these constructors add the widget to the `active` list, which is processed later when loading the workspace and calls fromVariantMap() on each of them.

The issue was fixed by removing the `active << this;` in the first constructor, but probably this is not the best solution.

**Comment by ThomasKroes** [comment]
This has been fixed in the mean time
