### ISSUE TITLE
quazip links dynamically to zlib but zlib dll is not copied to the install folder(s)

### ISSUE THREAD

**Issue by jeggermont** [ManiVaultStudio/core#634]
It seems with Zlib 1211 links dynamically to zlib but the zlib1.dll is not copied to the install folder and instead some other zlib1.dll on your path is loaded.

**Comment by alxvth** [comment]
This only happens with the DevBundle, right? We should probably add a small install command for externally provided zlibs.

As a quick workaround you could ignore the pre-compiled zlib with `--skip_binary ZLib1211`. The core repo will then automatically fetch a newer zlib version, compile and install it, see [here](https://github.com/ManiVaultStudio/core/blob/c118f2ad7a52d8df3363b63f3e33b9184a835c71/ManiVault/CMakeLists.txt#L125).

**Comment by alxvth** [comment]
Addressed in #635
