### ISSUE TITLE
Crash on Open Project

### ISSUE THREAD

**Issue by alxvth** [ManiVaultStudio/core#710]
When opening a project while a dataset is loaded, the application crashes.

Steps to reproduce:
1. Open ManiVault, open a new project with the data hierarchy and load any data
2. Try to open an existing project
3. Crash 

Note that no plugins where opened apart from a data loader plugin.

Maybe related to #703.

**Comment by ThomasKroes** [comment]
I attempted to reproduce the crash on my machine. At this point, I haven't been successful (yet). I must be overlooking something.

![CrashOnOpenProject](https://github.com/user-attachments/assets/e20f04c4-2238-4ed2-a83c-9eb9c4cf45ad)

**Comment by alxvth** [comment]
Updated the steps to reproduce above: The crash only occurs when the data hierarchy is open (or maybe other system/view plugins).
